# Generated by Django 6.0.5 on 2026-07-20 18:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_enrollment_completed_enrollment_completed_date_and_more'),
        ('dashboard', '0003_org_owner_user_id'),
        ('users', '0002_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('STARTING', 'Starting'), ('INGESTING_DOCUMENTS', 'Ingesting documents'), ('RESEARCHING', 'Researching'), ('DESIGNING_CURRICULUM', 'Designing curriculum'), ('WAITING_FOR_BLUEPRINT_APPROVAL', 'Waiting for blueprint approval'), ('GENERATING_LESSONS', 'Generating lessons'), ('GENERATING_ASSESSMENTS', 'Generating assessments'), ('GENERATING_FLASHCARDS', 'Generating flashcards'), ('REVIEWING', 'Reviewing'), ('REVISION_REQUIRED', 'Revision required'), ('WAITING_FOR_FINAL_APPROVAL', 'Waiting for final approval'), ('PERSISTING', 'Persisting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCEL_REQUESTED', 'Cancellation requested'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=50)),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status_message', models.TextField(blank=True)),
                ('course_brief', models.JSONField(default=dict)),
                ('input_config', models.JSONField(blank=True, default=dict)),
                ('graph_thread_id', models.CharField(blank=True, max_length=255)),
                ('graph_checkpoint_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('waiting_since', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_jobs', to='dashboard.org')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='users.user')),
                ('result_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='courses.course')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_jobs', to='dashboard.tutor')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GenerationJobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('STARTING', 'Starting'), ('INGESTING_DOCUMENTS', 'Ingesting documents'), ('RESEARCHING', 'Researching'), ('DESIGNING_CURRICULUM', 'Designing curriculum'), ('WAITING_FOR_BLUEPRINT_APPROVAL', 'Waiting for blueprint approval'), ('GENERATING_LESSONS', 'Generating lessons'), ('GENERATING_ASSESSMENTS', 'Generating assessments'), ('GENERATING_FLASHCARDS', 'Generating flashcards'), ('REVIEWING', 'Reviewing'), ('REVISION_REQUIRED', 'Revision required'), ('WAITING_FOR_FINAL_APPROVAL', 'Waiting for final approval'), ('PERSISTING', 'Persisting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCEL_REQUESTED', 'Cancellation requested'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai.generationjob')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='generationjob',
            index=models.Index(fields=['organization', 'status', '-created_at'], name='ai_generati_organiz_b8974d_idx'),
        ),
        migrations.AddIndex(
            model_name='generationjobevent',
            index=models.Index(fields=['job', 'created_at'], name='ai_generati_job_id_3a7970_idx'),
        ),
    ]
