# Generated by Django 6.0.5 on 2026-07-21 19:50

import ai.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=ai.models.source_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='UPLOADED', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('character_count', models.PositiveBigIntegerField(default=0)),
                ('extraction_task_id', models.CharField(blank=True, max_length=255)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='ai.generationjob')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SourceChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('character_count', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.sourcedocument')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('job', 'sha256'), name='unique_source_document_per_job'),
        ),
        migrations.AddIndex(
            model_name='sourcechunk',
            index=models.Index(fields=['document', 'page_number'], name='ai_sourcech_documen_8e7b3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcechunk',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='unique_source_chunk_position'),
        ),
    ]
