# Generated by Django 6.0.5 on 2026-07-21 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_sourcedocument_sourcechunk_and_more'),
        ('users', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('STARTING', 'Starting'), ('INGESTING_DOCUMENTS', 'Ingesting documents'), ('RESEARCHING', 'Researching'), ('DESIGNING_CURRICULUM', 'Designing curriculum'), ('BLUEPRINT_APPROVED', 'Blueprint approved'), ('WAITING_FOR_BLUEPRINT_APPROVAL', 'Waiting for blueprint approval'), ('GENERATING_LESSONS', 'Generating lessons'), ('GENERATING_ASSESSMENTS', 'Generating assessments'), ('GENERATING_FLASHCARDS', 'Generating flashcards'), ('REVIEWING', 'Reviewing'), ('REVISION_REQUIRED', 'Revision required'), ('WAITING_FOR_FINAL_APPROVAL', 'Waiting for final approval'), ('PERSISTING', 'Persisting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCEL_REQUESTED', 'Cancellation requested'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='generationjobevent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('STARTING', 'Starting'), ('INGESTING_DOCUMENTS', 'Ingesting documents'), ('RESEARCHING', 'Researching'), ('DESIGNING_CURRICULUM', 'Designing curriculum'), ('BLUEPRINT_APPROVED', 'Blueprint approved'), ('WAITING_FOR_BLUEPRINT_APPROVAL', 'Waiting for blueprint approval'), ('GENERATING_LESSONS', 'Generating lessons'), ('GENERATING_ASSESSMENTS', 'Generating assessments'), ('GENERATING_FLASHCARDS', 'Generating flashcards'), ('REVIEWING', 'Reviewing'), ('REVISION_REQUIRED', 'Revision required'), ('WAITING_FOR_FINAL_APPROVAL', 'Waiting for final approval'), ('PERSISTING', 'Persisting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCEL_REQUESTED', 'Cancellation requested'), ('CANCELLED', 'Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='GeneratedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BLUEPRINT', 'Curriculum blueprint')], max_length=30)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REVISION_REQUESTED', 'Revision requested'), ('SUPERSEDED', 'Superseded')], db_index=True, default='DRAFT', max_length=30)),
                ('content', models.JSONField(default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('source_document_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='ai.generationjob')),
            ],
            options={
                'ordering': ('type', '-version'),
            },
        ),
        migrations.CreateModel(
            name='ArtifactReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approve'), ('REVISE', 'Request revision')], max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifact_reviews', to='users.user')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ai.generatedartifact')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='generatedartifact',
            constraint=models.UniqueConstraint(fields=('job', 'type', 'version'), name='unique_generated_artifact_version'),
        ),
    ]
