# Generated by Django 6.0.5 on 2026-07-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_generationjob_status_and_more'),
        ('users', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artifactreview',
            constraint=models.UniqueConstraint(fields=('artifact',), name='one_review_per_artifact_version'),
        ),
    ]
