# Generated by Django 6.0.5 on 2026-07-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_artifactreview_one_review_per_artifact_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedartifact',
            name='type',
            field=models.CharField(choices=[('BLUEPRINT', 'Curriculum blueprint'), ('COURSE_PACKAGE', 'Generated course package')], max_length=30),
        ),
    ]
