# Generated by Django 6.0.5 on 2026-07-21 20:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_generatedartifact_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('NO_RESULTS', 'No results'), ('FAILED', 'Failed')], db_index=True, default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='ai.generationjob')),
            ],
            options={
                'ordering': ('priority', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DOCUMENT', 'Uploaded document'), ('WEB', 'Web source'), ('DATABASE', 'Database source')], max_length=20)),
                ('canonical_uri', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reliability_score', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_sources', to='ai.generationjob')),
            ],
            options={
                'ordering': ('-reliability_score', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ResearchFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim', models.TextField()),
                ('evidence', models.TextField()),
                ('confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('source_locator', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='ai.researchquestion')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='ai.researchsource')),
            ],
            options={
                'ordering': ('question__priority', '-confidence', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='researchquestion',
            constraint=models.UniqueConstraint(fields=('job', 'query'), name='unique_research_question_per_job'),
        ),
        migrations.AddConstraint(
            model_name='researchsource',
            constraint=models.UniqueConstraint(fields=('job', 'canonical_uri'), name='unique_research_source_per_job'),
        ),
    ]
