# Generated by Django 6.0.5 on 2026-07-21 20:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_researchquestion_researchsource_researchfinding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationjob',
            name='max_ai_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='generationjob',
            name='max_ai_tokens',
            field=models.PositiveIntegerField(default=250000),
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(db_index=True, max_length=100)),
                ('provider', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=255)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_records', to='ai.generationjob')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['job', 'operation', 'created_at'], name='ai_aiusager_job_id_6e28b6_idx')],
            },
        ),
    ]
