# Generated by Django 6.0.5 on 2026-07-21 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_generationjob_max_ai_cost_usd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationjob',
            name='max_ai_cost_usd',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
