"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-s52(hi4w2axqpsxp$)j*9#rl@uudwdvvg-r7ka^j@z=^##%*a@',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000,'
        'http://localhost:5173,http://127.0.0.1:5173',
    ).split(',')
    if origin.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'courses',
    'flashcards',
    'quizzes',
    'users',
    'ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


if os.environ.get('USE_SQLITE', 'False') == 'True':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'otto_lms'),
            'USER': os.environ.get('POSTGRES_USER', 'otto_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'otto_password'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))
SOURCE_DOCUMENT_MAX_BYTES = int(os.environ.get('SOURCE_DOCUMENT_MAX_BYTES', str(25 * 1024 * 1024)))

# Background course-generation jobs. PostgreSQL remains the source of truth for
# user-visible job state; Celery's result backend is intentionally not used for it.
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = None
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.environ.get('CELERY_TASK_TIME_LIMIT', '3600'))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.environ.get('CELERY_TASK_SOFT_TIME_LIMIT', '3300'))
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_DEFAULT_QUEUE = 'generation'
CELERY_TASK_ROUTES = {
    'ai.tasks.extract_source_document': {'queue': 'documents'},
    'ai.tasks.start_generation_job': {'queue': 'generation'},
    'ai.tasks.resume_generation_job': {'queue': 'generation'},
    'ai.tasks.recover_stalled_jobs': {'queue': 'maintenance'},
}
CELERY_BEAT_SCHEDULE = {
    'recover-stalled-generation-jobs': {
        'task': 'ai.tasks.recover_stalled_jobs',
        'schedule': int(os.environ.get('GENERATION_RECOVERY_INTERVAL_SECONDS', '300')),
    },
}

GENERATION_JOB_STALE_AFTER_SECONDS = int(
    os.environ.get('GENERATION_JOB_STALE_AFTER_SECONDS', '900')
)
GENERATION_WORKFLOW_RUNNER = os.environ.get(
    'GENERATION_WORKFLOW_RUNNER', 'ai.workflow.run_generation_workflow'
)
CURRICULUM_BLUEPRINT_GENERATOR = os.environ.get(
    'CURRICULUM_BLUEPRINT_GENERATOR', 'ai.generators.heuristic_blueprint_generator'
)
COURSE_PACKAGE_GENERATOR = os.environ.get(
    'COURSE_PACKAGE_GENERATOR', 'ai.generators.heuristic_course_package_generator'
)
COURSE_RESEARCH_PLANNER = os.environ.get(
    'COURSE_RESEARCH_PLANNER', 'ai.research.heuristic_research_planner'
)
COURSE_RESEARCH_PROVIDER = os.environ.get(
    'COURSE_RESEARCH_PROVIDER', 'ai.research.document_research_provider'
)
RESEARCH_MIN_RELIABILITY = float(os.environ.get('RESEARCH_MIN_RELIABILITY', '0.5'))
RESEARCH_MIN_CONFIDENCE = float(os.environ.get('RESEARCH_MIN_CONFIDENCE', '0.5'))
LANGGRAPH_DATABASE_URL = os.environ.get('LANGGRAPH_DATABASE_URL', '')
