# Generated by Django 6.0.5 on 2026-06-18 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_modules_for_existing_lessons(apps, schema_editor):
    Lesson = apps.get_model('courses', 'Lesson')
    Module = apps.get_model('courses', 'Module')

    module_cache = {}
    lessons = Lesson.objects.select_related('course').order_by('course_id', 'section_name', 'title')
    for lesson in lessons:
        title = lesson.section_name or 'Module'
        cache_key = (lesson.course_id, title)
        module = module_cache.get(cache_key)
        if module is None:
            module, _ = Module.objects.get_or_create(
                course_id=lesson.course_id,
                title=title,
                defaults={'order': len(module_cache), 'description': ''},
            )
            module_cache[cache_key] = module
        lesson.module_id = module.id
        lesson.save(update_fields=['module'])


def clear_lesson_modules(apps, schema_editor):
    Lesson = apps.get_model('courses', 'Lesson')
    Lesson.objects.update(module=None)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'ordering': ('order', 'title'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module'),
        ),
        migrations.RunPython(create_modules_for_existing_lessons, clear_lesson_modules),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='unique_course_module_title'),
        ),
    ]
