# Generated by Django 6.0.5 on 2026-06-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_module_lesson_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
