# Generated by Django 6.0.5 on 2026-06-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_position_module_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='position',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
