# Generated by Django 6.0.5 on 2026-06-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
