# Generated by Django 6.0.5 on 2026-07-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_org_description_alter_tutor_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='owner_user_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
