# Generated by Django 6.0.5 on 2026-06-29 19:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_attempt_student'),
        ('users', '0002_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='max_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('REORDER', 'Drag & Drop Reorder'), ('CATEGORIZE', 'Drag & Drop Categorize')], max_length=50),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question')),
            ],
            options={
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('best_score', models.FloatField(default=0.0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('last_attempted', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_progress', to='users.user')),
            ],
            options={
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
