import type { Quiz } from "./types";

export const quizzes: Quiz[] = [
  {
    id: 1,
    title: "React Hooks Fundamentals",
    description: "Test your knowledge of useState, useEffect, and custom hooks",
    status: "published",
    duration: "15 minutes",
    attempts: 234,
    avgScore: 78,
    courseId: "1",
    courseTitle: "React Fundamentals",
    createdAt: "2024-04-25",
    updatedAt: "2 hours ago",
    questions: [
      {
        id: 101,
        question: "Which hook stores local state in a function component?",
        type: "multiple-choice",
        points: 1,
        options: ["useState", "useEffect", "useMemo", "useRef"],
        correctAnswer: 0,
        hint: "Think about values that trigger re-rendering.",
      },
      {
        id: 102,
        question: "Select every hook that can help avoid unnecessary work.",
        type: "checkbox",
        points: 2,
        options: ["useMemo", "useCallback", "useId", "useEffect"],
        correctAnswer: [0, 1],
      },
      {
        id: 103,
        question: "useEffect always runs before the browser paints.",
        type: "true-false",
        points: 1,
        options: ["True", "False"],
        correctAnswer: 1,
      },
    ],
  },
  {
    id: 2,
    title: "TypeScript Types Quiz",
    description: "Challenge yourself with advanced TypeScript type concepts",
    status: "published",
    duration: "10 minutes",
    attempts: 156,
    avgScore: 85,
    courseId: "2",
    courseTitle: "TypeScript Advanced",
    createdAt: "2024-04-24",
    updatedAt: "1 day ago",
    questions: [
      {
        id: 201,
        question: "Match each TypeScript tool to its purpose.",
        type: "drag-drop-category",
        points: 3,
        options: ["Pick", "Omit", "Readonly", "Partial"],
        categories: ["Select properties", "Transform properties"],
        categoryMapping: {
          0: 0,
          1: 0,
          2: 1,
          3: 1,
        },
      },
      {
        id: 202,
        question: "Arrange the narrowing flow.",
        type: "drag-drop-order",
        points: 2,
        options: ["Receive union", "Check discriminator", "Access narrowed fields"],
      },
    ],
  },
  {
    id: 3,
    title: "Next.js Routing Quiz",
    description: "Test your understanding of Next.js App Router",
    status: "draft",
    duration: "8 minutes",
    attempts: 0,
    avgScore: 0,
    courseId: "3",
    courseTitle: "Next.js App Router",
    createdAt: "2024-04-23",
    updatedAt: "3 days ago",
    questions: [
      {
        id: 301,
        question: "Which file defines shared UI for nested routes?",
        type: "multiple-choice",
        points: 1,
        options: ["layout.tsx", "page.tsx", "route.ts", "template.css"],
        correctAnswer: 0,
      },
    ],
  },
  {
    id: 4,
    title: "SQL Optimization Quiz",
    description: "Challenge your database optimization skills",
    status: "published",
    duration: "12 minutes",
    attempts: 189,
    avgScore: 72,
    courseId: "4",
    courseTitle: "Database Design",
    createdAt: "2024-04-22",
    updatedAt: "5 days ago",
    questions: [
      {
        id: 401,
        question: "Indexes can speed up reads while adding write overhead.",
        type: "true-false",
        points: 1,
        options: ["True", "False"],
        correctAnswer: 0,
      },
    ],
  },
  {
    id: 5,
    title: "Python Basics Quiz",
    description: "Fundamental Python concepts and syntax",
    status: "draft",
    duration: "6 minutes",
    attempts: 0,
    avgScore: 0,
    courseId: "5",
    courseTitle: "Python for Beginners",
    createdAt: "2024-04-21",
    updatedAt: "1 week ago",
    questions: [
      {
        id: 501,
        question: "Which values are valid Python booleans?",
        type: "checkbox",
        points: 1,
        options: ["True", "False", "true", "false"],
        correctAnswer: [0, 1],
      },
    ],
  },
  {
    id: 6,
    title: "JavaScript ES6+ Quiz",
    description: "Modern JavaScript features and best practices",
    status: "published",
    duration: "10 minutes",
    attempts: 312,
    avgScore: 88,
    courseId: "6",
    courseTitle: "JavaScript ES6+",
    createdAt: "2024-04-20",
    updatedAt: "2 weeks ago",
    questions: [
      {
        id: 601,
        question: "Which keyword waits for a promise inside async functions?",
        type: "multiple-choice",
        points: 1,
        options: ["await", "defer", "yield", "then"],
        correctAnswer: 0,
      },
    ],
  },
];

export function getQuizById(id: number) {
  return quizzes.find((quiz) => quiz.id === id);
}
